version: '2'
services:
  web:
    container_name: nginx
    build: .
    restart: always
    ports:
      - '2020:80' # for testing purposes, (un)comment as required
    environment:
      - NGINX_PORT=80
