const countries = [
  { _id: 1, name: 'UNKNOWN' },
  { _id: 2, name: 'US: UNITED STATES' },
  { _id: 3, name: 'CA: CANADA' },
  { _id: 4, name: 'BJ: BENIN' },
  { _id: 5, name: 'AI: ANGUILLA' },
  { _id: 6, name: 'AG: ANTIGUA AND BARBUDA' },
  { _id: 7, name: 'PR: PUERTO RICO' },
  { _id: 8, name: 'KN: SAINT KITTS AND NEVIS' },
  { _id: 9, name: 'TT: TRINIDAD AND TOBAGO' },
  { _id: 10, name: 'TC: TURKS & CAICOS' },
  { _id: 11, name: 'LC: SAINT LUCIA' },
  { _id: 12, name: 'VC: ST. VINCENT & GRENADINES' },
  { _id: 13, name: 'BS: BAHAMAS' },
  { _id: 14, name: 'BM: BERMUDA' },
  { _id: 15, name: 'KY: CAYMAN ISLANDS' },
  { _id: 16, name: 'VG: VIRGIN ISLANDS, BRITISH' },
  { _id: 17, name: 'DM: DOMINICA' },
  { _id: 18, name: 'VI: VIRGIN ISLANDS, U.S.' },
  { _id: 19, name: 'AX: ALAND ISLANDS' },
  { _id: 20, name: 'BV: BOUVET ISLAND' },
  { _id: 21, name: 'IO: BRITISH INDIAN OCEAN TERR' },
  { _id: 22, name: 'TF: FRENCH SOUTHERN TERR' },
  { _id: 23, name: 'GG: GUERNSEY' },
  { _id: 24, name: 'HM: HEARD/MCDONALD ISLANDS' },
  { _id: 25, name: 'VA: HOLY SEE (VATICAN CITY)' },
  { _id: 26, name: 'IM: ISLE OF MAN' },
  { _id: 27, name: 'JE: JERSEY' },
  { _id: 28, name: 'DO: DOMINICAN REPUBLIC' },
  { _id: 29, name: 'NU: NIUE' },
  { _id: 30, name: 'NF: NORFOLK ISLAND' },
  { _id: 31, name: 'MP: NORTHERN MARIANA ISLANDS' },
  { _id: 32, name: 'PW: PALAU' },
  { _id: 33, name: 'PS: PALESTINIAN TERRITORY' },
  { _id: 34, name: 'RE: REUNION' },
  { _id: 35, name: 'BL: SAINT BARTHELEMY' },
  { _id: 36, name: 'MF: SAINT MARTIN' },
  { _id: 37, name: 'PM: SAINT PIERRE AND MIQUELON' },
  { _id: 38, name: 'ST: SAO TOME AND PRINCIPE' },
  { _id: 39, name: 'GS: S.GEORGIA&S.SANDWICH IS.' },
  { _id: 40, name: 'SJ: SVALBARD AND JAN MAYEN' },
  { _id: 41, name: 'TL: TIMOR-LESTE' },
  { _id: 42, name: 'TK: TOKELAU' },
  { _id: 43, name: 'WF: WALLIS AND FUTUNIA' },
  { _id: 44, name: 'EH: WESTERN SAHARA' },
  { _id: 45, name: 'UM: U.S. MINOR OUTLYING IS.' },
  { _id: 46, name: 'JM: JAMAICA' },
  { _id: 47, name: 'MS: MONTSERRAT' },
  { _id: 48, name: 'EG: EGYPT' },
  { _id: 49, name: 'MA: MOROCCO' },
  { _id: 50, name: 'DZ: ALGERIA' },
  { _id: 51, name: 'TN: TUNISIA' },
  { _id: 52, name: 'LY: LIBYAN ARAB JAMAHIRIYA' },
  { _id: 53, name: 'GM: GAMBIA' },
  { _id: 54, name: 'SN: SENEGAL' },
  { _id: 55, name: 'MR: MAURITANIA' },
  { _id: 56, name: 'ML: MALI' },
  { _id: 57, name: 'GN: GUINEA' },
  { _id: 58, name: "CI: COTE D'IVOIRE" },
  { _id: 59, name: 'BF: BUKINA FASO' },
  { _id: 60, name: 'NE: NIGER' },
  { _id: 61, name: 'TG: TOGO' },
  { _id: 62, name: 'MU: MAURITIUS' },
  { _id: 63, name: 'LR: LIBERIA' },
  { _id: 64, name: 'SL: SIERRA LEONE' },
  { _id: 65, name: 'GH: GHANA' },
  { _id: 66, name: 'NG: NIGERIA' },
  { _id: 67, name: 'TD: CHAD' },
  { _id: 68, name: 'CF: CENTRAL AFRICAN REPUBLIC' },
  { _id: 69, name: 'CM: CAMEROON' },
  { _id: 70, name: 'CV: CAPE VERDE ISLANDS' },
  { _id: 71, name: 'GQ: EQUATORIAL GUINEA' },
  { _id: 72, name: 'GA: GABON' },
  { _id: 73, name: 'CG: CONGO' },
  { _id: 74, name: 'CD: CONGO, DEM REP OF' },
  { _id: 75, name: 'AO: ANGOLA' },
  { _id: 76, name: 'GW: GUINEA-BISSAU' },
  { _id: 77, name: 'SC: SEYCHELLES' },
  { _id: 78, name: 'SD: SUDAN' },
  { _id: 79, name: 'RW: RWANDA' },
  { _id: 80, name: 'ET: ETHIOPIA' },
  { _id: 81, name: 'SO: SOMALIA' },
  { _id: 82, name: 'DJ: DJIBOUTI' },
  { _id: 83, name: 'KE: KENYA' },
  { _id: 84, name: 'TZ: TANZANIA' },
  { _id: 85, name: 'UG: UGANDA' },
  { _id: 86, name: 'BI: BURUNDI' },
  { _id: 87, name: 'MZ: MOZANBIQUE' },
  { _id: 88, name: 'ZM: ZAMBIA' },
  { _id: 89, name: 'MG: MADAGASCAR' },
  { _id: 90, name: 'ZW: ZIMBABWE' },
  { _id: 91, name: 'NA: NAMIBIA' },
  { _id: 92, name: 'MW: MALAWI' },
  { _id: 93, name: 'LS: LESOTHO' },
  { _id: 94, name: 'BW: BOTSWANA' },
  { _id: 95, name: 'SZ: SWAZILAND' },
  { _id: 96, name: 'KM: COMOROS' },
  { _id: 97, name: 'YT: MAYOTTE' },
  { _id: 98, name: 'ZA: SOUTH AFRICA' },
  { _id: 99, name: 'SH: SAINT HELENA' },
  { _id: 100, name: 'ER: ERITREA' },
  { _id: 101, name: 'AW: ARUBA' },
  { _id: 102, name: 'FO: FAROE ISLANDS' },
  { _id: 103, name: 'GL: GREENLAND' },
  { _id: 104, name: 'GR: GREECE' },
  { _id: 105, name: 'NL: NETHERLANDS' },
  { _id: 106, name: 'BE: BELGIUM' },
  { _id: 107, name: 'FR: FRANCE' },
  { _id: 108, name: 'MC: MONACO' },
  { _id: 109, name: 'ES: SPAIN' },
  { _id: 110, name: 'GI: GIBRALTAR' },
  { _id: 111, name: 'LU: LUXEMBOURG' },
  { _id: 112, name: 'IE: IRELAND' },
  { _id: 113, name: 'IS: ICELAND' },
  { _id: 114, name: 'AL: ALBANIA' },
  { _id: 115, name: 'MT: MALTA' },
  { _id: 116, name: 'CY: CYPRUS' },
  { _id: 117, name: 'FI: FINLAND' },
  { _id: 118, name: 'BG: BULGARIA' },
  { _id: 119, name: 'HU: HUNGARY' },
  { _id: 120, name: 'PT: PORTUGAL' },
  { _id: 121, name: 'LT: LITHUANIA' },
  { _id: 122, name: 'LV: LATVIA' },
  { _id: 123, name: 'EE: ESTONIA' },
  { _id: 124, name: 'MD: REPUBLIC OF MOLDOVA' },
  { _id: 125, name: 'AM: ARMENIA' },
  { _id: 126, name: 'BY: BELARUS' },
  { _id: 127, name: 'AD: ANDORRA' },
  { _id: 128, name: 'SM: SAN MARINO' },
  { _id: 129, name: 'UA: UKRAINE' },
  { _id: 130, name: 'RS: SERBIA' },
  { _id: 131, name: 'ME: MONTENEGRO' },
  { _id: 132, name: 'HR: CROATIA' },
  { _id: 133, name: 'SI: SLOVENIA' },
  { _id: 134, name: 'BA: BOSNIA HERZEGOVINA' },
  { _id: 135, name: 'MK: MACEDONIA' },
  { _id: 136, name: 'IT: ITALY' },
  { _id: 137, name: 'RO: ROMANIA' },
  { _id: 138, name: 'CH: SWITZERLAND' },
  { _id: 139, name: 'LI: LIECHTENSTEIN' },
  { _id: 140, name: 'CZ: CZECH REPUBLIC' },
  { _id: 141, name: 'SK: SLOVAKIA' },
  { _id: 142, name: 'AT: AUSTRIA' },
  { _id: 143, name: 'DK: DENMARK' },
  { _id: 144, name: 'SE: SWEDEN' },
  { _id: 145, name: 'NO: NORWAY' },
  { _id: 146, name: 'GD: GRENADA' },
  { _id: 147, name: 'PL: POLAND' },
  { _id: 148, name: 'DE: GERMANY' },
  { _id: 149, name: 'FK: FALKLAND ISLANDS' },
  { _id: 150, name: 'BZ: BELIZE' },
  { _id: 151, name: 'GT: GUATEMALA' },
  { _id: 152, name: 'SV: EL SALVADOR' },
  { _id: 153, name: 'HN: HONDURAS' },
  { _id: 154, name: 'NI: NICARAGUA' },
  { _id: 155, name: 'CR: COSTA RICA' },
  { _id: 156, name: 'PA: PANAMA' },
  { _id: 157, name: 'HT: HAITI' },
  { _id: 158, name: 'PE: PERU' },
  { _id: 159, name: 'MX: MEXICO' },
  { _id: 160, name: 'CU: CUBA' },
  { _id: 161, name: 'AR: ARGENTINA' },
  { _id: 162, name: 'BR: BRAZIL' },
  { _id: 163, name: 'CL: CHILE' },
  { _id: 164, name: 'CO: COLOMBIA' },
  { _id: 165, name: 'VE: VENEZUELA' },
  { _id: 166, name: 'GP: GUADELOUPE' },
  { _id: 167, name: 'BO: BOLIVIA' },
  { _id: 168, name: 'GY: GUYANA' },
  { _id: 169, name: 'EC: ECUADOR' },
  { _id: 170, name: 'GF: FRENCH GUIANA' },
  { _id: 171, name: 'PY: PARAGUAY' },
  { _id: 172, name: 'MQ: MARTINIQUE' },
  { _id: 173, name: 'SR: SURINAME' },
  { _id: 174, name: 'UY: URUGUAY' },
  { _id: 175, name: 'AN: NETHERLANDS ANTILLES' },
  { _id: 176, name: 'CW: CURACAO' },
  { _id: 177, name: 'MY: MALAYSIA' },
  { _id: 178, name: 'AU: AUSTRALIA' },
  { _id: 179, name: 'ID: INDONESIA' },
  { _id: 180, name: 'PH: PHILIPPINES' },
  { _id: 181, name: 'NZ: NEW ZEALAND' },
  { _id: 182, name: 'PN: PITCAIN ISLAND' },
  { _id: 183, name: 'SG: SINGAPORE' },
  { _id: 184, name: 'TH: THAILAND' },
  { _id: 185, name: 'GU: GUAM' },
  { _id: 186, name: 'AQ: ANTARCTIC AUS TERRITORY' },
  { _id: 187, name: 'CX: CHRISTMAS ISLAND' },
  { _id: 188, name: 'CC: COCOS ISLAND' },
  { _id: 189, name: 'BN: BRUNEI DARUSSALAM' },
  { _id: 190, name: 'NR: NAURU' },
  { _id: 191, name: 'PG: PAPUA NEW GUINEA' },
  { _id: 192, name: 'TO: TONGO' },
  { _id: 193, name: 'SB: SOLOM ISLANDS' },
  { _id: 194, name: 'VU: VANUATU' },
  { _id: 195, name: 'FJ: FIJI' },
  { _id: 196, name: 'CK: COOK ISLANDS' },
  { _id: 197, name: 'AS: AMERICAN SAMOA' },
  { _id: 198, name: 'WS: SAMOA' },
  { _id: 199, name: 'KI: KIRIBATI' },
  { _id: 200, name: 'NC: NEW CALEDONIA' },
  { _id: 201, name: 'TV: TUVALU' },
  { _id: 202, name: 'PF: FRENCH POLYNESIA' },
  { _id: 203, name: 'FM: MICRONESIA' },
  { _id: 204, name: 'MH: MARSHALL ISLANDS' },
  { _id: 205, name: 'KZ: KAZAKHSTAN' },
  { _id: 206, name: 'KG: KYRGYZSTAN' },
  { _id: 207, name: 'RU: RUSSIA' },
  { _id: 208, name: 'TJ: TAJIKISTAN' },
  { _id: 209, name: 'TM: TURKMENISTAN' },
  { _id: 210, name: 'UZ: UZBEKISTAN' },
  { _id: 211, name: 'BB: BARBADOS' },
  { _id: 212, name: 'JP: JAPAN' },
  { _id: 213, name: 'KR: KOREA, REPUBLIC OF' },
  { _id: 214, name: 'GB: UNITED KINGDOM' },
  { _id: 215, name: 'VN: VIETNAM' },
  { _id: 216, name: 'KP: KOREA (NORTH)' },
  { _id: 217, name: 'HK: HONG KONG' },
  { _id: 218, name: 'MO: MACAO' },
  { _id: 219, name: 'KH: CAMBODIA' },
  { _id: 220, name: 'LA: LAOS' },
  { _id: 221, name: 'CN: CHINA' },
  { _id: 222, name: 'TW: TAIWAN' },
  { _id: 223, name: 'BD: BANGLADESH' },
  { _id: 224, name: 'TR: TURKEY' },
  { _id: 225, name: 'IN: INDIA' },
  { _id: 226, name: 'PK: PAKISTAN' },
  { _id: 227, name: 'AF: AFGHANISTAN' },
  { _id: 228, name: 'LK: SRI LANKA' },
  { _id: 229, name: 'MM: MYANMAR(BURMA)' },
  { _id: 230, name: 'MV: MALDIVES' },
  { _id: 231, name: 'LB: LEBANON' },
  { _id: 232, name: 'JO: JORDAN' },
  { _id: 233, name: 'SY: SYRIA' },
  { _id: 234, name: 'IQ: IRAQ' },
  { _id: 235, name: 'KW: KUWAIT' },
  { _id: 236, name: 'SA: SAUDI ARABIA' },
  { _id: 237, name: 'YE: YEMEN' },
  { _id: 238, name: 'OM: OMAN' },
  { _id: 239, name: 'AE: UNITED ARAB EMIRATES' },
  { _id: 240, name: 'IL: ISRAEL' },
  { _id: 241, name: 'BH: BAHRAIN' },
  { _id: 242, name: 'QA: QATAR' },
  { _id: 243, name: 'BT: BHUTAN' },
  { _id: 244, name: 'MN: MONGOLIA' },
  { _id: 245, name: 'NP: NEPAL' },
  { _id: 246, name: 'IR: IRAN' },
  { _id: 247, name: 'AZ: AZERBAIJAN' },
  { _id: 248, name: 'GE: GEORGIA' },
  { _id: 249, name: 'EU: EUROPEAN UNION' },
  { _id: 250, name: 'MD: MOLDOVA' },
];
export default countries;
